### ISSUE TITLE
Link to official RPi Pico forum?

### ISSUE THREAD

**Issue by CHiPs44** [pinout-xyz/pico2.pinout.xyz#4]
Hello,

Would you mind adding a link to <https://forums.raspberrypi.com/viewforum.php?f=143> which is a valuable place to discuss about RPi Pico, too?

I can make a PR if necessary.

**Comment by Gadgetoid** [comment]
That's a solid idea, would need to do it on Pico and Pico W pages too- will look when I have a mo!

**Comment by Gadgetoid** [comment]
I think I've sorted this across all the sites, and tied them together nicely!

**Comment by CHiPs44** [comment]
Thanks!
